let
    Source = Table.NestedJoin(#"Sales Invoices GS", {"No_", "Sales Invoice Line.No_"}, #"Sales Invoices PN", {"Order No_", "Plenom Norge$Sales Invoice Line.No_"}, "Posted Sales Invoices PN", JoinKind.FullOuter),
    #"Expanded Posted Sales Invoices PN" = Table.ExpandTableColumn(Source, "Posted Sales Invoices PN", {"Bill-to Customer No_", "Bill-to Name", "Currency Code", "External Document No_", "No_", "Order Date", "Order No_", "Posting Date", "Sell-to Contact", "Sell-to Customer Name", "Sell-to Customer No_", "Ship-to Address", "Ship-to Address 2", "Ship-to City", "Ship-to Code", "Ship-to Contact", "Ship-to Country_Region Code", "Ship-to County", "Ship-to Name", "Ship-to Name 2", "Ship-to Post Code", "Your Reference", "Plenom Norge$Sales Invoice Line.Document No_", "Plenom Norge$Sales Invoice Line.Line No_", "Plenom Norge$Sales Invoice Line.No_", "Plenom Norge$Sales Invoice Line.Description", "Plenom Norge$Sales Invoice Line.Quantity", "Plenom Norge$Sales Invoice Line.Unit Price", "Plenom Norge$Sales Invoice Line.Amount", "Plenom Norge$Sales Invoice Line.Amount Including VAT"}, {"Posted Sales Invoices PN.Bill-to Customer No_", "Posted Sales Invoices PN.Bill-to Name", "Posted Sales Invoices PN.Currency Code", "Posted Sales Invoices PN.External Document No_", "Posted Sales Invoices PN.No_", "Posted Sales Invoices PN.Order Date", "Posted Sales Invoices PN.Order No_", "Posted Sales Invoices PN.Posting Date", "Posted Sales Invoices PN.Sell-to Contact", "Posted Sales Invoices PN.Sell-to Customer Name", "Posted Sales Invoices PN.Sell-to Customer No_", "Posted Sales Invoices PN.Ship-to Address", "Posted Sales Invoices PN.Ship-to Address 2", "Posted Sales Invoices PN.Ship-to City", "Posted Sales Invoices PN.Ship-to Code", "Posted Sales Invoices PN.Ship-to Contact", "Posted Sales Invoices PN.Ship-to Country_Region Code", "Posted Sales Invoices PN.Ship-to County", "Posted Sales Invoices PN.Ship-to Name", "Posted Sales Invoices PN.Ship-to Name 2", "Posted Sales Invoices PN.Ship-to Post Code", "Posted Sales Invoices PN.Your Reference", "Posted Sales Invoices PN.Plenom Norge$Sales Invoice Line.Document No_", "Posted Sales Invoices PN.Plenom Norge$Sales Invoice Line.Line No_", "Posted Sales Invoices PN.Plenom Norge$Sales Invoice Line.No_", "Posted Sales Invoices PN.Plenom Norge$Sales Invoice Line.Description", "Posted Sales Invoices PN.Plenom Norge$Sales Invoice Line.Quantity", "Posted Sales Invoices PN.Plenom Norge$Sales Invoice Line.Unit Price", "Posted Sales Invoices PN.Plenom Norge$Sales Invoice Line.Amount", "Posted Sales Invoices PN.Plenom Norge$Sales Invoice Line.Amount Including VAT"})
in
    #"Expanded Posted Sales Invoices PN"
	
	
	
	
let
    Source = Table.NestedJoin(#"Sales Credit Memos GS", {"No_", "Globe Systems A_S$Sales Cr_Memo Line.No_"}, #"Sales Credit Memos PN", {"Pre-Assigned No_", "Plenom Norge$Sales Cr_Memo Line.No_"}, "Posted Sales Credit Memo PN", JoinKind.FullOuter),
    #"Expanded Posted Sales Credit Memo PN" = Table.ExpandTableColumn(Source, "Posted Sales Credit Memo PN", {"Currency Code", "External Document No_", "No_", "Posting Date", "Pre-Assigned No_", "Return Order No_", "Sell-to Contact", "Sell-to Customer Name", "Sell-to Customer No_", "Plenom Norge$Sales Cr_Memo Line.Amount", "Plenom Norge$Sales Cr_Memo Line.Amount Including VAT", "Plenom Norge$Sales Cr_Memo Line.Unit Price"}, {"Posted Sales Credit Memo PN.Currency Code", "Posted Sales Credit Memo PN.External Document No_", "Posted Sales Credit Memo PN.No_", "Posted Sales Credit Memo PN.Posting Date", "Posted Sales Credit Memo PN.Pre-Assigned No_", "Posted Sales Credit Memo PN.Return Order No_", "Posted Sales Credit Memo PN.Sell-to Contact", "Posted Sales Credit Memo PN.Sell-to Customer Name", "Posted Sales Credit Memo PN.Sell-to Customer No_", "Posted Sales Credit Memo PN.Plenom Norge$Sales Cr_Memo Line.Amount", "Posted Sales Credit Memo PN.Plenom Norge$Sales Cr_Memo Line.Amount Including VAT", "Posted Sales Credit Memo PN.Plenom Norge$Sales Cr_Memo Line.Unit Price"})
in
    #"Expanded Posted Sales Credit Memo PN"